### ISSUE TITLE
All my files on the laptop are gone after running alc.sh

### ISSUE THREAD

**Issue by meredithw166** [louridas/hadoop-shortest-paths#1]
I didn't clone the repo and I downloaded it in the home directory instead. And after running your alc.sh, the disaster happened......ALL files on my laptop were GONE. Jesus Christ! Why you use rm -rf without --preserve-root?! And why you use -rf on earth... Yeah and I should take a look at your script before I ran it...

**Comment by louridas** [comment]
I am sorry for that, but alc.sh cleans up the output Hadoop directory. This should not be /. 

Note that --preserve-root does not exist on all systems. I can change the script to check that indeed the root is not passed as argument. Or you can send me a pull request.
